# Generated by Django 5.0.1 on 2024-02-06 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('B', 'Birth'), ('D', 'Death'), ('M', 'Marriage'), ('G', 'Graduation'), ('M', 'Military Service'), ('R', 'Relocation'), ('O', 'Other')], default='B', max_length=1)),
                ('event_date', models.DateField()),
                ('event_description', models.TextField(blank=True)),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.familymember')),
            ],
        ),
    ]
