# Generated by Django 5.0.1 on 2024-02-06 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_lifeevent_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='main_app.familymember')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='main_app.familymember')),
            ],
            options={
                'unique_together': {('parent', 'child')},
            },
        ),
        migrations.AddField(
            model_name='familymember',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', through='main_app.ParentChild', to='main_app.familymember'),
        ),
    ]
