# Generated by Django 5.0.2 on 2024-02-08 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_familymember_parents_familymember_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lifeevent',
            name='comments',
        ),
    ]
