# Generated by Django 5.0.2 on 2024-02-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_lifeevent_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='comments',
            field=models.ManyToManyField(to='main_app.comment'),
        ),
    ]
